app = "thelobby-sol-api"
primary_region = "fra"

[build]

[env]
  MIX_ENV = "prod"
  PORT = "4000"
  PHX_HOST = "api.the-lobby.pro"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "2s"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "./bin/thelobby_sol eval \"ThelobbySol.Release.migrate\""
