app = "thelobby-sol-api"
primary_region = "fra"

[build]

[env]
  MIX_ENV = "prod"
  PORT = "4000"
  PHX_HOST = "thelobby-sol-api.fly.dev"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "2s"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "thelobby_data"
  destination = "/app/data"

[deploy]
  release_command = "mix ecto.migrate"

[[services]]
  protocol = "tcp"
  internal_port = 4000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "1s"
