app = "thelobby-sol-frontend"
primary_region = "fra"

[build]
  [build.args]
    VITE_API_URL = "https://thelobby-sol-api.fly.dev"
    VITE_SOLANA_NETWORK = "devnet"
    VITE_PROGRAM_ID = "HackathonSkillTokenProgram111111111111111"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "2s"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 250
